server:
  port: 8081

im:
  server:
    address: 127.0.0.1
    port: 9091

spring:
  redis:
    host: xx.xx.xx.xx
    port: 6379
    password: xxxxxxxx
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xx.xx.xx.xx:3306/im?characterEncoding=utf-8&useSSL=false
    username: xxxxxxxx
    password: xxxxxxxx
mybatis-plus:
  mapper-locations: classpath*:xml
rocketmq:
  nameServers: xx.xx.xx.xx:9876
  producer:
    topic: im_inet_topic
    topic2: im_business_topic
    topic3: business_im_topic