// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BusinessMessage.proto

package org.example.common.po;

public final class Business {
  private Business() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BusinessMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.common.po.BusinessMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int32 userPlatformId = 3;</code>
     * @return The userPlatformId.
     */
    int getUserPlatformId();

    /**
     * <code>string userMacId = 4;</code>
     * @return The userMacId.
     */
    java.lang.String getUserMacId();
    /**
     * <code>string userMacId = 4;</code>
     * @return The bytes for userMacId.
     */
    com.google.protobuf.ByteString
        getUserMacIdBytes();

    /**
     * <code>int64 receiveId = 5;</code>
     * @return The receiveId.
     */
    long getReceiveId();

    /**
     * <code>int64 timeStamp = 6;</code>
     * @return The timeStamp.
     */
    long getTimeStamp();

    /**
     * <code>string msgBody = 7;</code>
     * @return The msgBody.
     */
    java.lang.String getMsgBody();
    /**
     * <code>string msgBody = 7;</code>
     * @return The bytes for msgBody.
     */
    com.google.protobuf.ByteString
        getMsgBodyBytes();

    /**
     * <code>bool needAck = 8;</code>
     * @return The needAck.
     */
    boolean getNeedAck();

    /**
     * <code>int32 businessType = 9;</code>
     * @return The businessType.
     */
    int getBusinessType();
  }
  /**
   * Protobuf type {@code org.example.common.po.BusinessMessage}
   */
  public static final class BusinessMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.common.po.BusinessMessage)
      BusinessMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BusinessMessage.newBuilder() to construct.
    private BusinessMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BusinessMessage() {
      id_ = "";
      userMacId_ = "";
      msgBody_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BusinessMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BusinessMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              userId_ = input.readInt64();
              break;
            }
            case 24: {

              userPlatformId_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userMacId_ = s;
              break;
            }
            case 40: {

              receiveId_ = input.readInt64();
              break;
            }
            case 48: {

              timeStamp_ = input.readInt64();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              msgBody_ = s;
              break;
            }
            case 64: {

              needAck_ = input.readBool();
              break;
            }
            case 72: {

              businessType_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.common.po.Business.internal_static_org_example_common_po_BusinessMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.common.po.Business.internal_static_org_example_common_po_BusinessMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.common.po.Business.BusinessMessage.class, org.example.common.po.Business.BusinessMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int USERPLATFORMID_FIELD_NUMBER = 3;
    private int userPlatformId_;
    /**
     * <code>int32 userPlatformId = 3;</code>
     * @return The userPlatformId.
     */
    @java.lang.Override
    public int getUserPlatformId() {
      return userPlatformId_;
    }

    public static final int USERMACID_FIELD_NUMBER = 4;
    private volatile java.lang.Object userMacId_;
    /**
     * <code>string userMacId = 4;</code>
     * @return The userMacId.
     */
    @java.lang.Override
    public java.lang.String getUserMacId() {
      java.lang.Object ref = userMacId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userMacId_ = s;
        return s;
      }
    }
    /**
     * <code>string userMacId = 4;</code>
     * @return The bytes for userMacId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserMacIdBytes() {
      java.lang.Object ref = userMacId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userMacId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVEID_FIELD_NUMBER = 5;
    private long receiveId_;
    /**
     * <code>int64 receiveId = 5;</code>
     * @return The receiveId.
     */
    @java.lang.Override
    public long getReceiveId() {
      return receiveId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private long timeStamp_;
    /**
     * <code>int64 timeStamp = 6;</code>
     * @return The timeStamp.
     */
    @java.lang.Override
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int MSGBODY_FIELD_NUMBER = 7;
    private volatile java.lang.Object msgBody_;
    /**
     * <code>string msgBody = 7;</code>
     * @return The msgBody.
     */
    @java.lang.Override
    public java.lang.String getMsgBody() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msgBody_ = s;
        return s;
      }
    }
    /**
     * <code>string msgBody = 7;</code>
     * @return The bytes for msgBody.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBodyBytes() {
      java.lang.Object ref = msgBody_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgBody_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NEEDACK_FIELD_NUMBER = 8;
    private boolean needAck_;
    /**
     * <code>bool needAck = 8;</code>
     * @return The needAck.
     */
    @java.lang.Override
    public boolean getNeedAck() {
      return needAck_;
    }

    public static final int BUSINESSTYPE_FIELD_NUMBER = 9;
    private int businessType_;
    /**
     * <code>int32 businessType = 9;</code>
     * @return The businessType.
     */
    @java.lang.Override
    public int getBusinessType() {
      return businessType_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (userPlatformId_ != 0) {
        output.writeInt32(3, userPlatformId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userMacId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userMacId_);
      }
      if (receiveId_ != 0L) {
        output.writeInt64(5, receiveId_);
      }
      if (timeStamp_ != 0L) {
        output.writeInt64(6, timeStamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgBody_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, msgBody_);
      }
      if (needAck_ != false) {
        output.writeBool(8, needAck_);
      }
      if (businessType_ != 0) {
        output.writeInt32(9, businessType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (userPlatformId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userPlatformId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userMacId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userMacId_);
      }
      if (receiveId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, receiveId_);
      }
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, timeStamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msgBody_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, msgBody_);
      }
      if (needAck_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, needAck_);
      }
      if (businessType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, businessType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.common.po.Business.BusinessMessage)) {
        return super.equals(obj);
      }
      org.example.common.po.Business.BusinessMessage other = (org.example.common.po.Business.BusinessMessage) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getUserPlatformId()
          != other.getUserPlatformId()) return false;
      if (!getUserMacId()
          .equals(other.getUserMacId())) return false;
      if (getReceiveId()
          != other.getReceiveId()) return false;
      if (getTimeStamp()
          != other.getTimeStamp()) return false;
      if (!getMsgBody()
          .equals(other.getMsgBody())) return false;
      if (getNeedAck()
          != other.getNeedAck()) return false;
      if (getBusinessType()
          != other.getBusinessType()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + USERPLATFORMID_FIELD_NUMBER;
      hash = (53 * hash) + getUserPlatformId();
      hash = (37 * hash) + USERMACID_FIELD_NUMBER;
      hash = (53 * hash) + getUserMacId().hashCode();
      hash = (37 * hash) + RECEIVEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiveId());
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
      hash = (37 * hash) + NEEDACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedAck());
      hash = (37 * hash) + BUSINESSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getBusinessType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.common.po.Business.BusinessMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.common.po.Business.BusinessMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.common.po.Business.BusinessMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.common.po.Business.BusinessMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.common.po.Business.BusinessMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.common.po.Business.BusinessMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.common.po.Business.BusinessMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.common.po.Business.BusinessMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.common.po.Business.BusinessMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.common.po.Business.BusinessMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.common.po.Business.BusinessMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.common.po.Business.BusinessMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.common.po.Business.BusinessMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.common.po.BusinessMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.common.po.BusinessMessage)
        org.example.common.po.Business.BusinessMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.common.po.Business.internal_static_org_example_common_po_BusinessMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.common.po.Business.internal_static_org_example_common_po_BusinessMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.common.po.Business.BusinessMessage.class, org.example.common.po.Business.BusinessMessage.Builder.class);
      }

      // Construct using org.example.common.po.Business.BusinessMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        userId_ = 0L;

        userPlatformId_ = 0;

        userMacId_ = "";

        receiveId_ = 0L;

        timeStamp_ = 0L;

        msgBody_ = "";

        needAck_ = false;

        businessType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.common.po.Business.internal_static_org_example_common_po_BusinessMessage_descriptor;
      }

      @java.lang.Override
      public org.example.common.po.Business.BusinessMessage getDefaultInstanceForType() {
        return org.example.common.po.Business.BusinessMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.common.po.Business.BusinessMessage build() {
        org.example.common.po.Business.BusinessMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.common.po.Business.BusinessMessage buildPartial() {
        org.example.common.po.Business.BusinessMessage result = new org.example.common.po.Business.BusinessMessage(this);
        result.id_ = id_;
        result.userId_ = userId_;
        result.userPlatformId_ = userPlatformId_;
        result.userMacId_ = userMacId_;
        result.receiveId_ = receiveId_;
        result.timeStamp_ = timeStamp_;
        result.msgBody_ = msgBody_;
        result.needAck_ = needAck_;
        result.businessType_ = businessType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.common.po.Business.BusinessMessage) {
          return mergeFrom((org.example.common.po.Business.BusinessMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.common.po.Business.BusinessMessage other) {
        if (other == org.example.common.po.Business.BusinessMessage.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getUserPlatformId() != 0) {
          setUserPlatformId(other.getUserPlatformId());
        }
        if (!other.getUserMacId().isEmpty()) {
          userMacId_ = other.userMacId_;
          onChanged();
        }
        if (other.getReceiveId() != 0L) {
          setReceiveId(other.getReceiveId());
        }
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        if (!other.getMsgBody().isEmpty()) {
          msgBody_ = other.msgBody_;
          onChanged();
        }
        if (other.getNeedAck() != false) {
          setNeedAck(other.getNeedAck());
        }
        if (other.getBusinessType() != 0) {
          setBusinessType(other.getBusinessType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.common.po.Business.BusinessMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.common.po.Business.BusinessMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 2;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private int userPlatformId_ ;
      /**
       * <code>int32 userPlatformId = 3;</code>
       * @return The userPlatformId.
       */
      @java.lang.Override
      public int getUserPlatformId() {
        return userPlatformId_;
      }
      /**
       * <code>int32 userPlatformId = 3;</code>
       * @param value The userPlatformId to set.
       * @return This builder for chaining.
       */
      public Builder setUserPlatformId(int value) {
        
        userPlatformId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userPlatformId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserPlatformId() {
        
        userPlatformId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userMacId_ = "";
      /**
       * <code>string userMacId = 4;</code>
       * @return The userMacId.
       */
      public java.lang.String getUserMacId() {
        java.lang.Object ref = userMacId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userMacId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userMacId = 4;</code>
       * @return The bytes for userMacId.
       */
      public com.google.protobuf.ByteString
          getUserMacIdBytes() {
        java.lang.Object ref = userMacId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userMacId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userMacId = 4;</code>
       * @param value The userMacId to set.
       * @return This builder for chaining.
       */
      public Builder setUserMacId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userMacId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userMacId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserMacId() {
        
        userMacId_ = getDefaultInstance().getUserMacId();
        onChanged();
        return this;
      }
      /**
       * <code>string userMacId = 4;</code>
       * @param value The bytes for userMacId to set.
       * @return This builder for chaining.
       */
      public Builder setUserMacIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userMacId_ = value;
        onChanged();
        return this;
      }

      private long receiveId_ ;
      /**
       * <code>int64 receiveId = 5;</code>
       * @return The receiveId.
       */
      @java.lang.Override
      public long getReceiveId() {
        return receiveId_;
      }
      /**
       * <code>int64 receiveId = 5;</code>
       * @param value The receiveId to set.
       * @return This builder for chaining.
       */
      public Builder setReceiveId(long value) {
        
        receiveId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 receiveId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiveId() {
        
        receiveId_ = 0L;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>int64 timeStamp = 6;</code>
       * @return The timeStamp.
       */
      @java.lang.Override
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>int64 timeStamp = 6;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timeStamp = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object msgBody_ = "";
      /**
       * <code>string msgBody = 7;</code>
       * @return The msgBody.
       */
      public java.lang.String getMsgBody() {
        java.lang.Object ref = msgBody_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msgBody_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msgBody = 7;</code>
       * @return The bytes for msgBody.
       */
      public com.google.protobuf.ByteString
          getMsgBodyBytes() {
        java.lang.Object ref = msgBody_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgBody_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgBody = 7;</code>
       * @param value The msgBody to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgBody = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgBody() {
        
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }
      /**
       * <code>string msgBody = 7;</code>
       * @param value The bytes for msgBody to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msgBody_ = value;
        onChanged();
        return this;
      }

      private boolean needAck_ ;
      /**
       * <code>bool needAck = 8;</code>
       * @return The needAck.
       */
      @java.lang.Override
      public boolean getNeedAck() {
        return needAck_;
      }
      /**
       * <code>bool needAck = 8;</code>
       * @param value The needAck to set.
       * @return This builder for chaining.
       */
      public Builder setNeedAck(boolean value) {
        
        needAck_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool needAck = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeedAck() {
        
        needAck_ = false;
        onChanged();
        return this;
      }

      private int businessType_ ;
      /**
       * <code>int32 businessType = 9;</code>
       * @return The businessType.
       */
      @java.lang.Override
      public int getBusinessType() {
        return businessType_;
      }
      /**
       * <code>int32 businessType = 9;</code>
       * @param value The businessType to set.
       * @return This builder for chaining.
       */
      public Builder setBusinessType(int value) {
        
        businessType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 businessType = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearBusinessType() {
        
        businessType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.common.po.BusinessMessage)
    }

    // @@protoc_insertion_point(class_scope:org.example.common.po.BusinessMessage)
    private static final org.example.common.po.Business.BusinessMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.common.po.Business.BusinessMessage();
    }

    public static org.example.common.po.Business.BusinessMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BusinessMessage>
        PARSER = new com.google.protobuf.AbstractParser<BusinessMessage>() {
      @java.lang.Override
      public BusinessMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BusinessMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BusinessMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BusinessMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.common.po.Business.BusinessMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_common_po_BusinessMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_common_po_BusinessMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025BusinessMessage.proto\022\025org.example.com" +
      "mon.po\"\266\001\n\017BusinessMessage\022\n\n\002id\030\001 \001(\t\022\016" +
      "\n\006userId\030\002 \001(\003\022\026\n\016userPlatformId\030\003 \001(\005\022\021" +
      "\n\tuserMacId\030\004 \001(\t\022\021\n\treceiveId\030\005 \001(\003\022\021\n\t" +
      "timeStamp\030\006 \001(\003\022\017\n\007msgBody\030\007 \001(\t\022\017\n\007need" +
      "Ack\030\010 \001(\010\022\024\n\014businessType\030\t \001(\005B#\n\025org.e" +
      "xample.common.poB\010BusinessH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_common_po_BusinessMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_common_po_BusinessMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_common_po_BusinessMessage_descriptor,
        new java.lang.String[] { "Id", "UserId", "UserPlatformId", "UserMacId", "ReceiveId", "TimeStamp", "MsgBody", "NeedAck", "BusinessType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
