// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package org.example.common.po;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChatMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.common.po.ChatMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>int32 userPlatformId = 3;</code>
     * @return The userPlatformId.
     */
    int getUserPlatformId();

    /**
     * <code>string userMacId = 4;</code>
     * @return The userMacId.
     */
    String getUserMacId();
    /**
     * <code>string userMacId = 4;</code>
     * @return The bytes for userMacId.
     */
    com.google.protobuf.ByteString
        getUserMacIdBytes();

    /**
     * <code>int64 receiveId = 5;</code>
     * @return The receiveId.
     */
    long getReceiveId();

    /**
     * <code>.org.example.common.po.ChatMessage.MsgType msgType = 6;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    int getMsgTypeValue();
    /**
     * <code>.org.example.common.po.ChatMessage.MsgType msgType = 6;</code>
     * @return The msgType.
     */
    ChatMessage.MsgType getMsgType();

    /**
     * <code>int64 timeStamp = 7;</code>
     * @return The timeStamp.
     */
    long getTimeStamp();

    /**
     * <code>bytes msgBody = 8;</code>
     * @return The msgBody.
     */
    com.google.protobuf.ByteString getMsgBody();

    /**
     * <code>bool needAck = 9;</code>
     * @return The needAck.
     */
    boolean getNeedAck();
  }
  /**
   * Protobuf type {@code org.example.common.po.ChatMessage}
   */
  public static final class ChatMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.common.po.ChatMessage)
      ChatMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ChatMessage.newBuilder() to construct.
    private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ChatMessage() {
      id_ = "";
      userMacId_ = "";
      msgType_ = 0;
      msgBody_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ChatMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ChatMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 16: {

              userId_ = input.readInt64();
              break;
            }
            case 24: {

              userPlatformId_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              userMacId_ = s;
              break;
            }
            case 40: {

              receiveId_ = input.readInt64();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              msgType_ = rawValue;
              break;
            }
            case 56: {

              timeStamp_ = input.readInt64();
              break;
            }
            case 66: {

              msgBody_ = input.readBytes();
              break;
            }
            case 72: {

              needAck_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Chat.internal_static_org_example_common_po_ChatMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Chat.internal_static_org_example_common_po_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMessage.class, Builder.class);
    }

    /**
     * Protobuf enum {@code org.example.common.po.ChatMessage.MsgType}
     */
    public enum MsgType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>TEXT = 0;</code>
       */
      TEXT(0),
      /**
       * <code>FILE = 1;</code>
       */
      FILE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>TEXT = 0;</code>
       */
      public static final int TEXT_VALUE = 0;
      /**
       * <code>FILE = 1;</code>
       */
      public static final int FILE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MsgType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MsgType forNumber(int value) {
        switch (value) {
          case 0: return TEXT;
          case 1: return FILE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MsgType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
              public MsgType findValueByNumber(int number) {
                return MsgType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ChatMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgType[] VALUES = values();

      public static MsgType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MsgType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.example.common.po.ChatMessage.MsgType)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @Override
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private long userId_;
    /**
     * <code>int64 userId = 2;</code>
     * @return The userId.
     */
    @Override
    public long getUserId() {
      return userId_;
    }

    public static final int USERPLATFORMID_FIELD_NUMBER = 3;
    private int userPlatformId_;
    /**
     * <code>int32 userPlatformId = 3;</code>
     * @return The userPlatformId.
     */
    @Override
    public int getUserPlatformId() {
      return userPlatformId_;
    }

    public static final int USERMACID_FIELD_NUMBER = 4;
    private volatile Object userMacId_;
    /**
     * <code>string userMacId = 4;</code>
     * @return The userMacId.
     */
    @Override
    public String getUserMacId() {
      Object ref = userMacId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userMacId_ = s;
        return s;
      }
    }
    /**
     * <code>string userMacId = 4;</code>
     * @return The bytes for userMacId.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserMacIdBytes() {
      Object ref = userMacId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userMacId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVEID_FIELD_NUMBER = 5;
    private long receiveId_;
    /**
     * <code>int64 receiveId = 5;</code>
     * @return The receiveId.
     */
    @Override
    public long getReceiveId() {
      return receiveId_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 6;
    private int msgType_;
    /**
     * <code>.org.example.common.po.ChatMessage.MsgType msgType = 6;</code>
     * @return The enum numeric value on the wire for msgType.
     */
    @Override public int getMsgTypeValue() {
      return msgType_;
    }
    /**
     * <code>.org.example.common.po.ChatMessage.MsgType msgType = 6;</code>
     * @return The msgType.
     */
    @Override public MsgType getMsgType() {
      @SuppressWarnings("deprecation")
      MsgType result = MsgType.valueOf(msgType_);
      return result == null ? MsgType.UNRECOGNIZED : result;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 7;
    private long timeStamp_;
    /**
     * <code>int64 timeStamp = 7;</code>
     * @return The timeStamp.
     */
    @Override
    public long getTimeStamp() {
      return timeStamp_;
    }

    public static final int MSGBODY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString msgBody_;
    /**
     * <code>bytes msgBody = 8;</code>
     * @return The msgBody.
     */
    @Override
    public com.google.protobuf.ByteString getMsgBody() {
      return msgBody_;
    }

    public static final int NEEDACK_FIELD_NUMBER = 9;
    private boolean needAck_;
    /**
     * <code>bool needAck = 9;</code>
     * @return The needAck.
     */
    @Override
    public boolean getNeedAck() {
      return needAck_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (userId_ != 0L) {
        output.writeInt64(2, userId_);
      }
      if (userPlatformId_ != 0) {
        output.writeInt32(3, userPlatformId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userMacId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userMacId_);
      }
      if (receiveId_ != 0L) {
        output.writeInt64(5, receiveId_);
      }
      if (msgType_ != MsgType.TEXT.getNumber()) {
        output.writeEnum(6, msgType_);
      }
      if (timeStamp_ != 0L) {
        output.writeInt64(7, timeStamp_);
      }
      if (!msgBody_.isEmpty()) {
        output.writeBytes(8, msgBody_);
      }
      if (needAck_ != false) {
        output.writeBool(9, needAck_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, userId_);
      }
      if (userPlatformId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, userPlatformId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userMacId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userMacId_);
      }
      if (receiveId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, receiveId_);
      }
      if (msgType_ != MsgType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, msgType_);
      }
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, timeStamp_);
      }
      if (!msgBody_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, msgBody_);
      }
      if (needAck_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(9, needAck_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChatMessage)) {
        return super.equals(obj);
      }
      ChatMessage other = (ChatMessage) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (getUserPlatformId()
          != other.getUserPlatformId()) return false;
      if (!getUserMacId()
          .equals(other.getUserMacId())) return false;
      if (getReceiveId()
          != other.getReceiveId()) return false;
      if (msgType_ != other.msgType_) return false;
      if (getTimeStamp()
          != other.getTimeStamp()) return false;
      if (!getMsgBody()
          .equals(other.getMsgBody())) return false;
      if (getNeedAck()
          != other.getNeedAck()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + USERPLATFORMID_FIELD_NUMBER;
      hash = (53 * hash) + getUserPlatformId();
      hash = (37 * hash) + USERMACID_FIELD_NUMBER;
      hash = (53 * hash) + getUserMacId().hashCode();
      hash = (37 * hash) + RECEIVEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiveId());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + msgType_;
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (37 * hash) + MSGBODY_FIELD_NUMBER;
      hash = (53 * hash) + getMsgBody().hashCode();
      hash = (37 * hash) + NEEDACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedAck());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChatMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChatMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChatMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ChatMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ChatMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChatMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.common.po.ChatMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.common.po.ChatMessage)
        ChatMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Chat.internal_static_org_example_common_po_ChatMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Chat.internal_static_org_example_common_po_ChatMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChatMessage.class, Builder.class);
      }

      // Construct using org.example.common.po.Chat.ChatMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = "";

        userId_ = 0L;

        userPlatformId_ = 0;

        userMacId_ = "";

        receiveId_ = 0L;

        msgType_ = 0;

        timeStamp_ = 0L;

        msgBody_ = com.google.protobuf.ByteString.EMPTY;

        needAck_ = false;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Chat.internal_static_org_example_common_po_ChatMessage_descriptor;
      }

      @Override
      public ChatMessage getDefaultInstanceForType() {
        return ChatMessage.getDefaultInstance();
      }

      @Override
      public ChatMessage build() {
        ChatMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ChatMessage buildPartial() {
        ChatMessage result = new ChatMessage(this);
        result.id_ = id_;
        result.userId_ = userId_;
        result.userPlatformId_ = userPlatformId_;
        result.userMacId_ = userMacId_;
        result.receiveId_ = receiveId_;
        result.msgType_ = msgType_;
        result.timeStamp_ = timeStamp_;
        result.msgBody_ = msgBody_;
        result.needAck_ = needAck_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChatMessage) {
          return mergeFrom((ChatMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChatMessage other) {
        if (other == ChatMessage.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getUserPlatformId() != 0) {
          setUserPlatformId(other.getUserPlatformId());
        }
        if (!other.getUserMacId().isEmpty()) {
          userMacId_ = other.userMacId_;
          onChanged();
        }
        if (other.getReceiveId() != 0L) {
          setReceiveId(other.getReceiveId());
        }
        if (other.msgType_ != 0) {
          setMsgTypeValue(other.getMsgTypeValue());
        }
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.getMsgBody() != com.google.protobuf.ByteString.EMPTY) {
          setMsgBody(other.getMsgBody());
        }
        if (other.getNeedAck() != false) {
          setNeedAck(other.getNeedAck());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ChatMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ChatMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 2;</code>
       * @return The userId.
       */
      @Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private int userPlatformId_ ;
      /**
       * <code>int32 userPlatformId = 3;</code>
       * @return The userPlatformId.
       */
      @Override
      public int getUserPlatformId() {
        return userPlatformId_;
      }
      /**
       * <code>int32 userPlatformId = 3;</code>
       * @param value The userPlatformId to set.
       * @return This builder for chaining.
       */
      public Builder setUserPlatformId(int value) {
        
        userPlatformId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 userPlatformId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserPlatformId() {
        
        userPlatformId_ = 0;
        onChanged();
        return this;
      }

      private Object userMacId_ = "";
      /**
       * <code>string userMacId = 4;</code>
       * @return The userMacId.
       */
      public String getUserMacId() {
        Object ref = userMacId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          userMacId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string userMacId = 4;</code>
       * @return The bytes for userMacId.
       */
      public com.google.protobuf.ByteString
          getUserMacIdBytes() {
        Object ref = userMacId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          userMacId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userMacId = 4;</code>
       * @param value The userMacId to set.
       * @return This builder for chaining.
       */
      public Builder setUserMacId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userMacId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string userMacId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserMacId() {
        
        userMacId_ = getDefaultInstance().getUserMacId();
        onChanged();
        return this;
      }
      /**
       * <code>string userMacId = 4;</code>
       * @param value The bytes for userMacId to set.
       * @return This builder for chaining.
       */
      public Builder setUserMacIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userMacId_ = value;
        onChanged();
        return this;
      }

      private long receiveId_ ;
      /**
       * <code>int64 receiveId = 5;</code>
       * @return The receiveId.
       */
      @Override
      public long getReceiveId() {
        return receiveId_;
      }
      /**
       * <code>int64 receiveId = 5;</code>
       * @param value The receiveId to set.
       * @return This builder for chaining.
       */
      public Builder setReceiveId(long value) {
        
        receiveId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 receiveId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearReceiveId() {
        
        receiveId_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ = 0;
      /**
       * <code>.org.example.common.po.ChatMessage.MsgType msgType = 6;</code>
       * @return The enum numeric value on the wire for msgType.
       */
      @Override public int getMsgTypeValue() {
        return msgType_;
      }
      /**
       * <code>.org.example.common.po.ChatMessage.MsgType msgType = 6;</code>
       * @param value The enum numeric value on the wire for msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgTypeValue(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.common.po.ChatMessage.MsgType msgType = 6;</code>
       * @return The msgType.
       */
      @Override
      public MsgType getMsgType() {
        @SuppressWarnings("deprecation")
        MsgType result = MsgType.valueOf(msgType_);
        return result == null ? MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.example.common.po.ChatMessage.MsgType msgType = 6;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        msgType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.example.common.po.ChatMessage.MsgType msgType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>int64 timeStamp = 7;</code>
       * @return The timeStamp.
       */
      @Override
      public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>int64 timeStamp = 7;</code>
       * @param value The timeStamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timeStamp = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msgBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes msgBody = 8;</code>
       * @return The msgBody.
       */
      @Override
      public com.google.protobuf.ByteString getMsgBody() {
        return msgBody_;
      }
      /**
       * <code>bytes msgBody = 8;</code>
       * @param value The msgBody to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msgBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes msgBody = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgBody() {
        
        msgBody_ = getDefaultInstance().getMsgBody();
        onChanged();
        return this;
      }

      private boolean needAck_ ;
      /**
       * <code>bool needAck = 9;</code>
       * @return The needAck.
       */
      @Override
      public boolean getNeedAck() {
        return needAck_;
      }
      /**
       * <code>bool needAck = 9;</code>
       * @param value The needAck to set.
       * @return This builder for chaining.
       */
      public Builder setNeedAck(boolean value) {
        
        needAck_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool needAck = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeedAck() {
        
        needAck_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.common.po.ChatMessage)
    }

    // @@protoc_insertion_point(class_scope:org.example.common.po.ChatMessage)
    private static final ChatMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChatMessage();
    }

    public static ChatMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChatMessage>
        PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
      @Override
      public ChatMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChatMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ChatMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChatMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public ChatMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_common_po_ChatMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_common_po_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021ChatMessage.proto\022\025org.example.common." +
      "po\"\370\001\n\013ChatMessage\022\n\n\002id\030\001 \001(\t\022\016\n\006userId" +
      "\030\002 \001(\003\022\026\n\016userPlatformId\030\003 \001(\005\022\021\n\tuserMa" +
      "cId\030\004 \001(\t\022\021\n\treceiveId\030\005 \001(\003\022;\n\007msgType\030" +
      "\006 \001(\0162*.org.example.common.po.ChatMessag" +
      "e.MsgType\022\021\n\ttimeStamp\030\007 \001(\003\022\017\n\007msgBody\030" +
      "\010 \001(\014\022\017\n\007needAck\030\t \001(\010\"\035\n\007MsgType\022\010\n\004TEX" +
      "T\020\000\022\010\n\004FILE\020\001B\037\n\025org.example.common.poB\004" +
      "ChatH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_common_po_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_common_po_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_common_po_ChatMessage_descriptor,
        new String[] { "Id", "UserId", "UserPlatformId", "UserMacId", "ReceiveId", "MsgType", "TimeStamp", "MsgBody", "NeedAck", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
